# Generated by Django 4.1.4 on 2023-01-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_expenses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
