# Generated by Django 4.1.4 on 2023-01-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_num_expenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='num_expenses',
        ),
    ]
